<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'APP_SECRET' => '19c205027c4ca79ed1ac31d114203e07',
  'DATABASE_URL' => 'mysql://root:root@127.0.0.1:8889/Mytest?serverVersion=8&charset=utf8mb4',
  'DB_USER' => 'root',
  'DB_PASSWORD' => 'root',
  'DB_NAME' => 'Mytest',
);
