<?php

namespace ContainerJlLaoRL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3T3yShc.App\Entity\News' shared service.
     *
     * @return \App\Entity\News
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3T3yShc": it needs an instance of "App\\Entity\\News" but this type has been excluded in "config/services.yaml".');
    }
}
