<?php

namespace ContainerU84alJl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VPS93hZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vPS93hZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vPS93hZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'news' => ['privates', '.errored..service_locator.vPS93hZ.App\\Entity\\News', NULL, 'Cannot autowire service ".service_locator.vPS93hZ": it needs an instance of "App\\Entity\\News" but this type has been excluded in "config/services.yaml".'],
        ], [
            'news' => 'App\\Entity\\News',
        ]);
    }
}
