<?php

namespace ContainerU84alJl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3T3yShcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3T3yShc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3T3yShc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'news' => ['privates', '.errored..service_locator.3T3yShc.App\\Entity\\News', NULL, 'Cannot autowire service ".service_locator.3T3yShc": it needs an instance of "App\\Entity\\News" but this type has been excluded in "config/services.yaml".'],
            'newsRepository' => ['privates', 'App\\Repository\\NewsRepository', 'getNewsRepositoryService', true],
        ], [
            'news' => 'App\\Entity\\News',
            'newsRepository' => 'App\\Repository\\NewsRepository',
        ]);
    }
}
