<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJlLaoRL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJlLaoRL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJlLaoRL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJlLaoRL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJlLaoRL\App_KernelDevDebugContainer([
    'container.build_hash' => 'JlLaoRL',
    'container.build_id' => '21ac1959',
    'container.build_time' => 1687611295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJlLaoRL');
