<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomeController::homepage'], [], [['text', '/']], [], [], []],
    'app_news_index' => [[], ['_controller' => 'App\\Controller\\NewsController::index'], [], [['text', '/news/']], [], [], []],
    'app_news_new' => [[], ['_controller' => 'App\\Controller\\NewsController::new'], [], [['text', '/news/new']], [], [], []],
    'app_news_show' => [['id'], ['_controller' => 'App\\Controller\\NewsController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/news']], [], [], []],
    'app_news_edit' => [['id'], ['_controller' => 'App\\Controller\\NewsController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/news']], [], [], []],
    'app_news_delete' => [['id'], ['_controller' => 'App\\Controller\\NewsController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/news']], [], [], []],
];
